version: '3.8'
services:
    moviebook-database-mongo-container:
        container_name: moviebook-database-mongo-container
        image: mongo:4.4.6
        ports:
            - "27017:27017"
        #environment:
            #MONGO_INITDB_ROOT_USERNAME: root
            #MONGO_INITDB_ROOT_PASSWORD: example