version: '3.8'
services:
    moviebook-database-container:
        container_name: moviebook-database-container
        image: postgres:12.5-alpine
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 123456
            POSTGRES_DB: moviebook-db

    moviebook-database-mongo-container:
        container_name: moviebook-database-mongo-container
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example