server:
  servlet:
    context-path: /moviebook
  port: 8081
  error:
    include-message: always

spring:
  data:
    mongodb:
      uri: mongodb://localhost/moviebook-database-mongo-container
  profiles:
    include: 'integration'